version: '3.6'
services:
  # webapp:
  #   build: ./webapp
  #   ports:
  # #     - '3000:3000'
  # gql:
  #   build: ./gql
  #   ports:
  #     - '4000:4000'
  #     - '9229:9229'
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   environment:
  #     - NODE_ENV=development
  # parser:
  #   build: ./parser
  #   ports: 
  #     - '5001:5001'
  #   tmpfs:
  #     - /tmp:exec,mode=777
  #   volumes:
  #     - ./parser:/parser
  #   depends_on:
  #     - parserdb
  # ml:
  #   build: ./ml
  #   ports:
  #     - '5002:5002'
  service:
    command: uvicorn app:app --reload --port ${SERVICE_PORT} --host 0.0.0.0
    build: 
      context: .
      dockerfile: ./${SERVICE_NAME}/Dockerfile
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    depends_on:
      - servicedb
    volumes:
      - ./${SERVICE_NAME}:/app
    environment:
      - WATCHFILES_FORCE_POLLING=true
  servicedb:
    image: amd64/postgres:alpine
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./${SERVICE_NAME}/config:/var/lib/postgres/data
      - ./${SERVICE_NAME}/config/setup/:/docker-entrypoint-initdb.d/
volumes:
  servicedb:
    driver: local