version: '3.6'
services:
  webapp:
    image: webapp:latest
    ports:
      - '3000:3000'
  gql:
    image: gql:latest
    ports:
      - '4000:4000'
      - '9229:9229'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
  parser:
    image: parser:latest
    ports: 
      - '5001:5001'
    tmpfs:
      - /tmp:exec,mode=777
  ml:
    image: ml:latest
    ports:
      - '5002:5002'
  db:
    image: db:latest
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres
      - POSGRES_PASSWORD=postgres
      - POSTGRES_DB=stratosphere
volumes:
  db:
    driver: local