version: '3.6'
services:
  # webapp:
  #   build: ./webapp
  #   ports:
  # #     - '3000:3000'
  # gql:
  #   build: ./gql
  #   ports:
  #     - '4000:4000'
  #     - '9229:9229'
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   environment:
  #     - NODE_ENV=development
  # parser:
  #   build: ./parser
  #   ports: 
  #     - '5001:5001'
  #   tmpfs:
  #     - /tmp:exec,mode=777
  #   volumes:
  #     - ./parser:/parser
  #   depends_on:
  #     - parserdb
  # ml:
  #   build: ./ml
  #   ports:
  #     - '5002:5002'
  replay:
    command: uvicorn app:app --reload --port ${REPLAY_SERVICE_PORT} --host 0.0.0.0
    build: 
      context: ./
      dockerfile: ./${REPLAY_SERVICE_NAME}/Dockerfile
    ports:
      - ${REPLAY_SERVICE_PORT}:${REPLAY_SERVICE_PORT}
    depends_on:
      - replaydb
      - redis
    volumes:
      - ./${REPLAY_SERVICE_NAME}:/app
      - .env:/app/.env
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
  replaydb:
    image: mongo:latest
    restart: always
    ports:
      - ${REPLAY_DB_PORT}:${REPLAY_DB_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${REPLAY_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${REPLAY_DB_PASSWORD}
    volumes:
      - ./${REPLAY_SERVICE_NAME}/config/db:/data/db
  redis:
    image: redis:6.2.10-alpine
  parser:
    build: 
      dockerfile: Dockerfile-worker
      context: ./replay/
    command: celery -A worker worker
    volumes:
      - .env:/worker/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - replay
volumes:
  replaydb:
    driver: local
  replay:
    external: true