version: '3.6'
services:
  # webapp:
  #   build: ./webapp
  #   ports:
  #     - '3000:3000'
  gql:
    build: ./gql
    ports:
      - '4000:4000'
      - '9229:9229'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
  parser:
    build: ./parser
    volumes: ['./parser:/parser']
    ports: 
      - '5001:5001'
    tmpfs:
      - /tmp:exec,mode=777
  ml:
    build: ./ml
    ports:
      - '5002:5002'
  db:
    build: ./db
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres
      - POSGRES_PASSWORD=postgres
      - POSTGRES_DB=stratosphere
volumes:
  db:
    driver: local