version: '3.6'
services:
  # webapp:
  #   build: ./webapp
  #   ports:
  #     - '3000:3000'
  gql:
    build: ./gql
    ports:
      - '4000:4000'
      - '9229:9229'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
  parser:
    build: ./parser
    ports: 
      - '5001:5001'
    tmpfs:
      - /tmp:exec,mode=777
    depends_on:
      - parserdb
  ml:
    build: ./ml
    ports:
      - '5002:5002'
  db:
    build: ./db
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stratosphere
  parserdb:
    image: postgres:14.0
    restart: always
    ports:
      - 6699:6699
    volumes:
      - db:/var/lib/postgres/data
      - ./parser/db:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1
      - POSTGRES_DB=parserdb
volumes:
  db:
    driver: local
  parserdb:
    driver: local