import dotenv

ENV_PATH = ".env"

dotenv.load_dotenv(dotenv_path=ENV_PATH)

SERVICE_VAR_NAME = "REPLAY_SERVICE_NAME"
SERVICE_VAR_PORT_NAME = "REPLAY_SERVICE_PORT"

DB_VAR_HOST_NAME = "REPLAY_DB_HOST"
DB_VAR_NAME = "REPLAY_DB_NAME"
DB_VAR_USER_NAME = "REPLAY_DB_USER"
DB_VAR_PASSWORD_NAME = "REPLAY_DB_PASSWORD"
DB_VAR_PORT_NAME = "REPLAY_DB_PORT"

SECRET_KEY_NAME = "REPLAY_USER_SECRET_KEY"
ENCODER_ALGORIGHTM_NAME = "REPLAY_ENCODE_ALGORITHM"
ADMIN_USER_NAME = "REPLAY_ADMIN_USER"
ADMIN_PASSWORD_NAME = "REPLAY_ADMIN_PASSWORD"