FROM nucypher/rust-python:3.8.12 

RUN apt-get update && apt-get install -y python3-pip
RUN python -m pip install --upgrade pip

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /worker

COPY ./parser/requirements.txt ./
RUN pip3 install -r requirements.txt

COPY ./schemas ./schemas
COPY ./repository ./repository
COPY ./services ./services
COPY ./util ./util
COPY ./config ./config

COPY ./parser /worker

EXPOSE 8000